sudo: required

language: java

services:
 - docker

script:
 - docker build -t wimkeir/green .
 - docker run wimkeir/green /bin/sh -c "ant; ant test;"
 - docker inspect --format="{{.Id}}" wimkeir/green
 - docker logs -t $?
